ALTER TABLE "Marche" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Marche" ADD COLUMN IF NOT EXISTS "clientInfo" TEXT;

ALTER TABLE "Devis" ADD COLUMN IF NOT EXISTS "clientInfo" TEXT;
ALTER TABLE "Devis" ADD COLUMN IF NOT EXISTS "notes" TEXT;

ALTER TABLE "Chantier" ADD COLUMN IF NOT EXISTS "contact" TEXT;

